### ISSUE TITLE
你好，我想請問下怎麼中文設置英文標點

### ISSUE THREAD

**Issue by zmj1368** [mritd/rime#1]
你好，我想請問下怎麼中文設置英文標點（it developer）

**Comment by mritd** [comment]
抱歉，没太理解什么意思；你是指在中文下输入的标点符号为英文么？

**Comment by zmj1368** [comment]
对，我是想在中文模式下输入的标点也是英文模式，也可以调回中文模式。还有emoji图没办法输出，请问有方法解决吗

**Comment by mritd** [comment]
@zmj1368 标点符号问题，你可以通过 `ctrl + ~` 快捷，在选项里切换

![image](https://user-images.githubusercontent.com/13043245/70303931-b2cae580-183b-11ea-948a-c27a28878b7c.png)

第五项用来切换标点符号状态，第六项用来切换编码集；默认 GBK 编码集下你输入快捷按键 `/bq` 等是不显示的，因为 UTF-8 编码集比较大，可能会出现生僻字，所以我的配置默认为 GBK 编码集；用过你想彻底解决这个问题，请编辑配置文件 https://github.com/mritd/rime/blob/81468e582d19f2dfb98fdccce71fc5cdc9d267f9/iMac-Home/luna_pinyin_simp.custom.yaml#L28

![image](https://user-images.githubusercontent.com/13043245/70304095-1c4af400-183c-11ea-83a2-4ea6782496fd.png)


通过调整默认顺序既可让输入法默认在某个配置上

**Comment by mritd** [comment]
UTF-8 下表情才可以输入

![image](https://user-images.githubusercontent.com/13043245/70304176-4d2b2900-183c-11ea-914a-bad6ee10ce5c.png)

![image](https://user-images.githubusercontent.com/13043245/70304155-413f6700-183c-11ea-8610-0bcadd2bd6a7.png)

**Comment by zmj1368** [comment]
😀非常棒，感谢您的释疑和配置
还有三个小问题：
1. UTF-8 编码集比较大，是害怕输入法会卡吗？ 生僻字应该还好吧，我把它改成utf-8默认有什么影响吗？
2. 目前试下来表情/bq等符号只能中文符号下使用,可以考虑在英文符号下也能用吗?
3. 他的词库貌似比较差，联想功能等于没有，有办法优化吗 ？

**Comment by mritd** [comment]
对于第一个和第三个问题，UTF-8 字符集包含的汉字比较多，而且大多数都是生僻字，在词库不是很理想的情况下候选词会出现过多的生僻词汇，影响输入效率；而现实情况就是我们无法拿到类似搜狗输入法这种云词库

第二个问题目前我不知道怎么设置...

**Comment by zmj1368** [comment]
在chrome浏览器框中直接输入有一个问题
![image](https://user-images.githubusercontent.com/17699649/70384448-74f3cb80-19b9-11ea-8303-33954624985c.png)
我无法选取下一页的字，safari是可以的， 你遇到过这样的情况吗？

**Comment by mritd** [comment]
这个问题从来没遇到过，我的 chrome 一直正常...
![image](https://user-images.githubusercontent.com/13043245/70400553-77602f00-1a66-11ea-9109-effa5dc74def.png)

**Comment by zmj1368** [comment]
![image](https://user-images.githubusercontent.com/17699649/70489451-c7a6c200-1b36-11ea-9d00-9b904f426f34.png)
按下键会和选择下方的内容有冲突，按右键会变成拼音。。。。很纠结
还有 qq表情能够集成进来吗

**Comment by mritd** [comment]
下方向键是预期行为，qq 表情等请问问 rime 作者
